# Generated by Django 4.2.7 on 2025-11-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="verified",
            field=models.BooleanField(default=False, help_text="Verified badge status"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="vin_id",
            field=models.CharField(
                blank=True,
                help_text="Unique VinVerse ID (e.g., VIN-0000001)",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
