# Generated by Django 4.2.7 on 2025-11-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_options_customuser_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_online",
            field=models.BooleanField(default=False, help_text="Online status"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_seen",
            field=models.DateTimeField(auto_now=True, help_text="Last seen timestamp"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="xp_points",
            field=models.IntegerField(
                default=0, help_text="XP points for gamification"
            ),
        ),
    ]
