# Generated by Django 4.2.7 on 2025-11-09 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_is_online_customuser_last_seen_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique badge identifier", max_length=50, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Badge display name", max_length=100),
                ),
                ("description", models.TextField(help_text="Badge description")),
                (
                    "icon",
                    models.CharField(
                        default="🏆", help_text="Badge icon/emoji", max_length=10
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("streak", "Login Streak"),
                            ("tournament", "Tournament"),
                            ("social", "Social"),
                            ("achievement", "Achievement"),
                        ],
                        default="achievement",
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="purple", help_text="Badge color theme", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
                "db_table": "badge",
                "ordering": ["badge_type", "name"],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_active_date",
            field=models.DateField(
                blank=True, help_text="Last date user was active", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="streak_days",
            field=models.IntegerField(
                default=0, help_text="Current login streak in days"
            ),
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the badge was earned"
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        help_text="Badge that was earned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to="accounts.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who earned the badge",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Badge",
                "verbose_name_plural": "User Badges",
                "db_table": "user_badge",
                "ordering": ["-earned_at"],
                "unique_together": {("user", "badge")},
            },
        ),
    ]
