# Generated by Django 4.2.7 on 2025-11-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("follow", "New Follower"),
                    ("team_invite", "Team Invitation"),
                    ("message", "New Message"),
                    ("tournament", "Tournament Update"),
                    ("ai_insight", "AI Insight Ready"),
                    ("like", "Post Liked"),
                    ("comment", "New Comment"),
                    ("post", "New Post"),
                ],
                max_length=20,
            ),
        ),
    ]
