# Generated by Django 5.2.5 on 2025-11-09 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this room (for private rooms)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_chat_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="is_private",
            field=models.BooleanField(
                default=False, help_text="Private rooms require invitation"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                help_text="Members of private rooms",
                related_name="chat_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("global", "Global Lobby"),
                    ("game", "Game Channel"),
                    ("team", "Team Room"),
                    ("private", "Private Room"),
                ],
                default="global",
                max_length=20,
            ),
        ),
    ]
