# Generated by Django 4.2.7 on 2025-11-09 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_room_created_by_room_is_private_room_members_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "is_invite",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is an invite from room creator, False if user requested",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message with request/invite",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="User who sent the invite/request (can be the same as user for self-requests)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_room_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        help_text="Private room being requested",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="chat.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting to join",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Join Request",
                "verbose_name_plural": "Room Join Requests",
                "db_table": "room_join_request",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["room", "status"], name="room_join_r_room_id_1d35bf_idx"
                    ),
                    models.Index(
                        fields=["user", "status"], name="room_join_r_user_id_49ae9c_idx"
                    ),
                ],
                "unique_together": {("room", "user", "status")},
            },
        ),
    ]
