# Generated by Django 4.2.7 on 2025-11-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_roomjoinrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_code",
            field=models.CharField(
                blank=True,
                help_text="Unique code for private rooms (e.g., 237601)",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
    ]
