# Generated by Django 4.2.7 on 2025-11-08 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Tournament name", max_length=200)),
                (
                    "game",
                    models.CharField(
                        help_text="Game title (e.g., Valorant, CS2)", max_length=100
                    ),
                ),
                ("date", models.DateTimeField(help_text="Tournament date and time")),
                (
                    "prize_pool",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Prize pool amount",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this tournament",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournaments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament",
                "verbose_name_plural": "Tournaments",
                "db_table": "tournament",
                "ordering": ["-date"],
            },
        ),
    ]
