# Generated by Django 4.2.7 on 2025-11-08 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this tournament",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_tournaments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="TournamentParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the user joined"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        help_text="Tournament the user joined",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who joined the tournament",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joined_tournaments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Participant",
                "verbose_name_plural": "Tournament Participants",
                "db_table": "tournament_participant",
                "ordering": ["-joined_at"],
                "unique_together": {("tournament", "user")},
            },
        ),
    ]
