# Generated by Django 4.2.7 on 2025-11-08 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tournaments", "0002_alter_tournament_created_by_tournamentparticipant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Team name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "game",
                    models.CharField(
                        help_text="Primary game (e.g., Valorant, BGMI)", max_length=100
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Region/timezone",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "play_style",
                    models.CharField(
                        choices=[
                            ("casual", "Casual"),
                            ("competitive", "Competitive"),
                            ("professional", "Professional"),
                        ],
                        default="casual",
                        max_length=50,
                    ),
                ),
                (
                    "max_members",
                    models.IntegerField(default=5, help_text="Maximum team size"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the team",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Team members",
                        related_name="teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "db_table": "team",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Post content", max_length=1000),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional post image",
                        null=True,
                        upload_to="posts/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("likes_count", models.IntegerField(default=0)),
                ("comments_count", models.IntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who created the post",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "db_table": "post",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LFTPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.CharField(
                        help_text="Game they want to play", max_length=100
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        blank=True, help_text="Current rank", max_length=100, null=True
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Region/timezone",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "play_style",
                    models.CharField(
                        choices=[
                            ("casual", "Casual"),
                            ("competitive", "Competitive"),
                            ("professional", "Professional"),
                        ],
                        default="casual",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(help_text="LFT message", max_length=500)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this LFT post still active?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User looking for team",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lft_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "LFT Post",
                "verbose_name_plural": "LFT Posts",
                "db_table": "lft_post",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary",
                    models.TextField(help_text="AI-generated performance summary"),
                ),
                (
                    "strengths",
                    models.JSONField(
                        default=list, help_text="List of identified strengths"
                    ),
                ),
                (
                    "improvements",
                    models.JSONField(
                        default=list, help_text="List of suggested improvements"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overall performance score (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_model",
                    models.CharField(
                        default="gpt-4",
                        help_text="AI model used for generation",
                        max_length=50,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        help_text="Tournament this insight is based on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this insight is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Insight",
                "verbose_name_plural": "Match Insights",
                "db_table": "match_insight",
                "ordering": ["-generated_at"],
                "unique_together": {("user", "tournament")},
            },
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_accepted",
                    models.BooleanField(
                        default=True, help_text="For future friend requests"
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        help_text="User who is following",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        help_text="User being followed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Friendship",
                "verbose_name_plural": "Friendships",
                "db_table": "friendship",
                "ordering": ["-created_at"],
                "unique_together": {("follower", "following")},
            },
        ),
    ]
