# Generated by Django 4.2.7 on 2025-11-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gamerlink",
            "0002_remove_post_comments_count_remove_post_likes_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lftpost",
            name="game_id",
            field=models.CharField(
                blank=True,
                help_text="In-game ID/Username for the game",
                max_length=100,
                null=True,
            ),
        ),
    ]
